import '../styles/globals.css'
// import { Inter } from 'next/font/google'

import { Poppins } from 'next/font/google';
// @import url('https://fonts.googleapis.com/css2?family=Open+Sans&display=swap');

import { Footer, Navbar } from '../components';
import { Hero } from '@/sections';
const poppins = Poppins({
  subsets: ['latin'],
  weight: ["300", "400", "500"],
  variable: '--font-poppins',
})

export const metadata = {
  title: 'Meta',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans `} >
        <div className='bg-slate-800 overflow-hidden '>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
       
        </div>
      </body>
    </html>
  )
}
